[2023-01-21T10:00:44.248+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-13T01:00:00+00:00 [queued]>
[2023-01-21T10:00:44.522+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-13T01:00:00+00:00 [queued]>
[2023-01-21T10:00:44.551+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T10:00:44.571+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-01-21T10:00:44.573+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T10:00:45.841+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read_csv> on 2022-01-13 01:00:00+00:00
[2023-01-21T10:00:46.222+0000] {standard_task_runner.py:54} INFO - Started process 6797 to run task
[2023-01-21T10:00:46.322+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'read_csv', 'scheduled__2022-01-13T01:00:00+00:00', '--job-id', '616', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmpu36yrkmk']
[2023-01-21T10:00:46.369+0000] {standard_task_runner.py:83} INFO - Job 616: Subtask read_csv
[2023-01-21T10:00:46.372+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-01-21T10:01:16.420+0000] {timeout.py:68} ERROR - Process timed out, PID: 6797
[2023-01-21T10:01:16.519+0000] {dagbag.py:330} ERROR - Failed to import: /opt/***/dags/real_estate_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estate_dag.py", line 5, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 143, in <module>
    from pandas.io.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/api.py", line 16, in <module>
    from pandas.io.json import read_json
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/__init__.py", line 1, in <module>
    from pandas.io.json._json import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/***/dags/real_estate_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://***.apache.org/docs/apache-***/2.4.1/best-practices.html#top-level-python-code
* https://***.apache.org/docs/apache-***/2.4.1/best-practices.html#reducing-dag-complexity, PID: 6797
[2023-01-21T10:01:16.580+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 616 for task read_csv (Dag 'real_estate_data_pipeline' could not be found; either it does not exist or it failed to parse.; 6797)
[2023-01-21T10:01:17.413+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-21T10:01:18.191+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
