[2023-01-21T11:21:43.456+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-23T11:00:00+00:00 [queued]>
[2023-01-21T11:21:43.564+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-23T11:00:00+00:00 [queued]>
[2023-01-21T11:21:43.565+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:21:43.565+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-01-21T11:21:43.566+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:21:43.633+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read_csv> on 2022-01-23 11:00:00+00:00
[2023-01-21T11:21:43.662+0000] {standard_task_runner.py:54} INFO - Started process 5302 to run task
[2023-01-21T11:21:43.703+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'read_csv', 'scheduled__2022-01-23T11:00:00+00:00', '--job-id', '1137', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmp0inuk_rk']
[2023-01-21T11:21:43.722+0000] {standard_task_runner.py:83} INFO - Job 1137: Subtask read_csv
[2023-01-21T11:21:43.744+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-01-21T11:21:45.125+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-23T11:00:00+00:00 [running]> on host 2fb4a96081a8
[2023-01-21T11:21:45.354+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=read_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-23T11:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-23T11:00:00+00:00
[2023-01-21T11:21:45.359+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estate_dag.py", line 30, in read_csv
    print('File esxist ?' + isExist)
TypeError: can only concatenate str (not "bool") to str
[2023-01-21T11:21:45.390+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_data_pipeline, task_id=read_csv, execution_date=20220123T110000, start_date=20230121T112143, end_date=20230121T112145
[2023-01-21T11:21:45.408+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1137 for task read_csv (can only concatenate str (not "bool") to str; 5302)
[2023-01-21T11:21:45.550+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-21T11:21:45.628+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
