[2023-01-21T12:15:07.701+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.clean_and_transform_data manual__2023-01-21T12:15:05.803982+00:00 [queued]>
[2023-01-21T12:15:07.710+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.clean_and_transform_data manual__2023-01-21T12:15:05.803982+00:00 [queued]>
[2023-01-21T12:15:07.710+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T12:15:07.711+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-01-21T12:15:07.711+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T12:15:07.719+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): clean_and_transform_data> on 2023-01-21 12:15:05.803982+00:00
[2023-01-21T12:15:07.724+0000] {standard_task_runner.py:54} INFO - Started process 1596 to run task
[2023-01-21T12:15:07.728+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'clean_and_transform_data', 'manual__2023-01-21T12:15:05.803982+00:00', '--job-id', '1206', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmp6qb10k27']
[2023-01-21T12:15:07.729+0000] {standard_task_runner.py:83} INFO - Job 1206: Subtask clean_and_transform_data
[2023-01-21T12:15:07.729+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-01-21T12:15:07.936+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.clean_and_transform_data manual__2023-01-21T12:15:05.803982+00:00 [running]> on host 9667f615f42a
[2023-01-21T12:15:07.979+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=clean_and_transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T12:15:05.803982+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-21T12:15:05.803982+00:00
[2023-01-21T12:15:07.987+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estate_dag.py", line 50, in clean_and_transform_data
    df = df.dropna()  # remove rows with missing values
AttributeError: 'dict' object has no attribute 'dropna'
[2023-01-21T12:15:07.996+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_data_pipeline, task_id=clean_and_transform_data, execution_date=20230121T121505, start_date=20230121T121507, end_date=20230121T121507
[2023-01-21T12:15:08.003+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1206 for task clean_and_transform_data ('dict' object has no attribute 'dropna'; 1596)
[2023-01-21T12:15:08.022+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-21T12:15:08.042+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
