[2023-01-21T11:21:39.568+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-23T03:00:00+00:00 [queued]>
[2023-01-21T11:21:39.616+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-23T03:00:00+00:00 [queued]>
[2023-01-21T11:21:39.620+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:21:39.622+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-01-21T11:21:39.623+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:21:39.715+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read_csv> on 2022-01-23 03:00:00+00:00
[2023-01-21T11:21:39.721+0000] {standard_task_runner.py:54} INFO - Started process 5284 to run task
[2023-01-21T11:21:39.806+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'read_csv', 'scheduled__2022-01-23T03:00:00+00:00', '--job-id', '1128', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmpvyuzrhh7']
[2023-01-21T11:21:39.819+0000] {standard_task_runner.py:83} INFO - Job 1128: Subtask read_csv
[2023-01-21T11:21:39.822+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-01-21T11:21:43.847+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-23T03:00:00+00:00 [running]> on host 2fb4a96081a8
[2023-01-21T11:21:44.224+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=read_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-23T03:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-23T03:00:00+00:00
[2023-01-21T11:21:44.230+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estate_dag.py", line 30, in read_csv
    print('File esxist ?' + isExist)
TypeError: can only concatenate str (not "bool") to str
[2023-01-21T11:21:44.275+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_data_pipeline, task_id=read_csv, execution_date=20220123T030000, start_date=20230121T112139, end_date=20230121T112144
[2023-01-21T11:21:44.307+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1128 for task read_csv (can only concatenate str (not "bool") to str; 5284)
[2023-01-21T11:21:44.540+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-21T11:21:44.700+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
