[2023-01-21T12:13:45.053+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.clean_and_transform_data manual__2023-01-21T12:08:40.713787+00:00 [queued]>
[2023-01-21T12:13:45.061+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.clean_and_transform_data manual__2023-01-21T12:08:40.713787+00:00 [queued]>
[2023-01-21T12:13:45.061+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T12:13:45.061+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-01-21T12:13:45.062+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T12:13:45.070+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): clean_and_transform_data> on 2023-01-21 12:08:40.713787+00:00
[2023-01-21T12:13:45.075+0000] {standard_task_runner.py:54} INFO - Started process 1526 to run task
[2023-01-21T12:13:45.080+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'clean_and_transform_data', 'manual__2023-01-21T12:08:40.713787+00:00', '--job-id', '1204', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmpt99cewjr']
[2023-01-21T12:13:45.081+0000] {standard_task_runner.py:83} INFO - Job 1204: Subtask clean_and_transform_data
[2023-01-21T12:13:45.082+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-01-21T12:13:45.665+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.clean_and_transform_data manual__2023-01-21T12:08:40.713787+00:00 [running]> on host 9667f615f42a
[2023-01-21T12:13:45.839+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=clean_and_transform_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T12:08:40.713787+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-21T12:08:40.713787+00:00
[2023-01-21T12:13:45.857+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estate_dag.py", line 46, in clean_and_transform_data
    df = json.loads(df)
NameError: name 'json' is not defined
[2023-01-21T12:13:45.882+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=real_estate_data_pipeline, task_id=clean_and_transform_data, execution_date=20230121T120840, start_date=20230121T121345, end_date=20230121T121345
[2023-01-21T12:13:45.896+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1204 for task clean_and_transform_data (name 'json' is not defined; 1526)
[2023-01-21T12:13:45.933+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-21T12:13:45.985+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
